version: "3"

services:
  main_build:
    build: .
    volumes:
      - ./:/Dory
    working_dir: /Dory
    command: make build
  config_build:
    build: .
    volumes:
      - ./:/Dory
    working_dir: /Dory
    command: make config

