version: "3"

services:
  main_build:
    build: .
    volumes:
      - ./:/Dumbo-NG
    working_dir: /Dumbo-NG
    command: make build
  config_build:
    build: .
    volumes:
      - ./:/Dumbo-NG
    working_dir: /Dumbo-NG
    command: make config

